### ISSUE TITLE
ReferenceError: config is not defined

### ISSUE THREAD

**Issue by fhemberger** [marcysutton/reveal-a11y#1]
I don't know if there's something missing, otherwise this line causes a ReferenceError:
https://github.com/marcysutton/reveal-a11y/blob/master/accessibility/helper.js#L88

Also `config` isn't used throughout the script again.

**Comment by marcysutton** [comment]
Weird, I have no idea where that line came from! My working copy does not include that, so I'd say it's safe to remove. Thanks for your contribution!

**Comment by fhemberger** [comment]
Cool, thanks! 🎉
